# Generated by Django 5.2 on 2025-05-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.FloatField(help_text='Response time in milliseconds')),
            ],
            options={
                'verbose_name': 'Login timing',
                'verbose_name_plural': 'Login timings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
